#포트설정
server:
  port: '8081'
#JSP설정
spring:
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix:  .jsp
#SMTP설정
  mail:
    host:  smtp.gmail.com
    prot: '587'
    username:  jjunyuongv@gmail.com
    password:  wpwi cgrr sfuk oltk
    properties:
      mail:
        debug:  'true'
        smtp:
          connectiontimeout:  '5000'
          auth:  'false'
          starttls:
            enable: 'true'
            required:  'true'    
